color0 #fcf8fd
color1 #ba1a1a
color2 #5056a9
color3 #5c5d72
color4 #78536b
color5 #bfc2ff
color6 #c5c4dd
color7 #1b1b1f
color8 #777680
color9 #ba1a1a
color10 #5056a9
color11 #5c5d72
color12 #78536b
color13 #bfc2ff
color14 #c5c4dd
color15 #1b1b1f

cursor                #1b1b1f
cursor_text_color     #fcf8fd
background            #fcf8fd
foreground            #1b1b1f
selection_foreground  #46464f
selection_background  #e4e1ec
active_border_color   #5056a9
inactive_border_color #e4e1ec
url_color             #5056a9

active_tab_foreground   #ffffff
active_tab_background   #5056a9
inactive_tab_foreground #46464f
inactive_tab_background #e4e1ec
cursor_trail_color      #46464f
