# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0xfcf8fdff
bordercolor = 0x777680ff
focuscolor = 0x5056a9ff
maximizescreencolor = 0x5c5d72ff
urgentcolor = 0xba1a1aff
scratchpadcolor = 0x78536bff
globalcolor = 0xe0e0ffff
overlaycolor = 0xe1e0f9ff
